# Generated by Django 3.1.4 on 2020-12-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_migrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
